version: "3"

services:
  django:
    build: .
    ports:
      - "8080:80"
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: pseudotest
      DB_PORT: 3306
      S3_BUCKET: none
    links:
      - "mariadb:mariadb"
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: "mariadb:10.1.34"
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: pseudotest
    restart: always
