# Generated by Django 2.2 on 2019-05-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudo_test', '0003_auto_20190430_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='file_id',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_in',
            field=models.CharField(default='[]', max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_out',
            field=models.CharField(default='[]', max_length=100),
        ),
    ]
