# Generated by Django 2.2 on 2019-05-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudo_test', '0005_auto_20190506_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
